#!/bin/bash
set -e -x
id
apt-get update
apt-get -y install apt-transport-https ca-certificates

echo deb https://people.debian.org/~doko/tmp/gcc8 ./ >> /etc/apt/sources.list
echo 'APT::Get::AllowUnauthenticated "1";' > /etc/apt/apt.conf.d/99allow-unauth
echo 'Binary::apt-get::Acquire::AllowInsecureRepositories "1";' >> /etc/apt/apt.conf.d/99allow-unauth
apt-get update
apt-get -y dist-upgrade
apt-get -y autoremove
apt-get remove --purge -y gcc-6-base
#apt-get -y install cpp g++ gcc
