#!/bin/sh
set -e -x
echo deb http://127.0.0.1:9999/debian experimental main >> /etc/apt/sources.list
cat <<-EOF > /etc/apt/preferences.d/pin-glibc-exp
Package: glibc-doc glibc-source libc6 libc6-dbg libc6-dev libc6-dev-i386 libc6-dev-x32 libc6-i386 libc6-pic libc6-udeb libc6-x32 libc-bin libc-dev-bin libc-l10n locales locales-all multiarch-support nscd
Pin: release o=Debian,a=experimental
Pin-Priority: 999
EOF
apt-get update
apt-get -y dist-upgrade
