#!/bin/bash
set -x
echo "Entering customization script..."

apt-get update
apt-get install libtinfo5
#apt-get -y install g++-multilib
#apt-get install -y gcc-4.4
#apt-get install -y g++-4.4
#apt-get install -y libstdc++
#apt-get install libc6-dev-i386
FOLDER=/home/compiler

#/tmp/dpkg-buildflags

echo "Replace clang, clang++, gcc, g++ & cpp by our compiler"
VERSIONS="6"
cd /usr/bin
for VERSION in $VERSIONS; do
    rm -f g++-$VERSION gcc-$VERSION cpp-$VERSION
    ln -s $FOLDER/llvm-install/bin/clang++ g++-$VERSION
    ln -s $FOLDER/llvm-install/bin/clang gcc-$VERSION
    ln -s $FOLDER/llvm-install/bin/clang cpp-$VERSION
    echo "gcc-$VERSION hold"|dpkg --set-selections
    echo "g++-$VERSION hold"|dpkg --set-selections
done
rm -f gcc
ln -s $FOLDER/llvm-install/bin/clang gcc
echo "gcc hold"|dpkg --set-selections
rm -f g++        
ln -s $FOLDER/llvm-install/bin/clang++ g++
echo "g++ hold"|dpkg --set-selections
rm -f cpp        
ln -s $FOLDER/llvm-install/bin/clang cpp
rm -f clang        
ln -s $FOLDER/llvm-install/bin/clang clang
echo "clang hold"|dpkg --set-selections
rm -f clang++
ln -s $FOLDER/llvm-install/bin/clang++ clang++
echo "clang++ hold"|dpkg --set-selections
cd -


